spring:
  profiles:
    active: "local"

  sql:
    init:
      continue-on-error: false
      platform: ${spring.profiles.active}
      schema-locations: "classpath:/database/schema.sql"
      data-locations:
        - "classpath:/database/data-users.sql"
  datasource:
    hikari:
      driver-class-name: "org.h2.Driver"

      # Embedded mode: run database on application process(JVM).
      jdbc-url: "jdbc:h2:mem:~/template_db;DB_CLOSE_DELAY=-1"

      username: "sa"
      password: ""
      connection-test-query: "SELECT 1"

  h2:
    console:
      enabled: true
      path: "/h2-console"

  thymeleaf:
    enabled: true
    encoding: "UTF-8"
    prefix: "classpath:/templates/"
    suffix: ".html"

server:
  port: 8080
